[package]
name = "rustconsensus"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
ctor = "*"
rstest = "*"
tokio = { version = "*", features = ["full"]}
tracing-subscriber = "*"

[dependencies]
#TODO version numbers
anyhow = "*"
async-trait = "*"
bytes = "*"
rand = "*"
rustc-hash = "*"
tokio = { version = "*", features = ["net", "sync", "macros"] } #TODO
tracing = "*"
