[package]
name = "rustconsensus"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
ctor = "*"
lazy_static = "*"
rstest = "*"
tokio = { version = "*", features = ["full"]}
tracing-subscriber = "*"

[dependencies]
#TODO version numbers
anyhow = "*"
bytes = "*"
rustc-hash = "*"
tokio = { version = "*", features = ["net", "sync", "macros"] } #TODO
tracing = "*"
log = "0.4.22"

